[package]
name = "syneroym-net"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
common.workspace = true
anyhow.workspace = true
tokio.workspace = true