[package]
name = "syneroym-protocol-http"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
common.workspace = true
app-host.workspace = true
protocol-base.workspace = true
anyhow.workspace = true
async-trait = "0.1"
